#preload = /home/andre/media/wallpapers/altimit-03.png
#wallpaper = , /home/andre/media/wallpapers/altimit-03.png

wallpaper {
    monitor = 
    path = /home/andre/media/wallpapers/altimit-03.png
    fit_mode = cover
}

splash = false
ipc = true
