#!/bin/sh

swayidle -w \
  timeout 300 'wlopm --off *' resume 'wlopm --on *' \
  timeout 600 'swaylock -f -c 000000' \
  before-sleep 'swaylock -f -c 000000' &

libinput-gestures-setup start &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
kanshi &
swayosd-server &
waybar --log-level off &

background_image="$HOME/media/zencold.png"
if [ -f "$background_image" ]; then
  swaybg -i "$background_image" -m fill &
else
  swaybg -c "#1a1b26" &
fi

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
